/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param enableStockManagement 
 * @param hideOutOfStockProducts 
 * @param enableLowStockNotifications 
 * @param enableOutOfStockNotifications 
 * @param stockNotificationRecipients 
 * @param holdStock 
 * @param lowStockThreshold 
 * @param outOfStockThreshold 
 * @param stockDisplayFormat 
 */


data class InventoryOptions (

    @Json(name = "enableStockManagement")
    val enableStockManagement: kotlin.Boolean? = null,

    @Json(name = "hideOutOfStockProducts")
    val hideOutOfStockProducts: kotlin.Boolean? = null,

    @Json(name = "enableLowStockNotifications")
    val enableLowStockNotifications: kotlin.Boolean? = null,

    @Json(name = "enableOutOfStockNotifications")
    val enableOutOfStockNotifications: kotlin.Boolean? = null,

    @Json(name = "stockNotificationRecipients")
    val stockNotificationRecipients: kotlin.String? = null,

    @Json(name = "holdStock")
    val holdStock: kotlin.Int? = null,

    @Json(name = "lowStockThreshold")
    val lowStockThreshold: kotlin.Int? = null,

    @Json(name = "outOfStockThreshold")
    val outOfStockThreshold: kotlin.Int? = null,

    @Json(name = "stockDisplayFormat")
    val stockDisplayFormat: InventoryOptions.StockDisplayFormat? = null

) {

    /**
     * 
     *
     * Values: AlwaysDisplayRemainingQuantity,OnlyDisplayRemainingQuantityWhenStockIsLow,NeverDisplayRemainingQuantity
     */
    @JsonClass(generateAdapter = false)
    enum class StockDisplayFormat(val value: kotlin.String) {
        @Json(name = "AlwaysDisplayRemainingQuantity") AlwaysDisplayRemainingQuantity("AlwaysDisplayRemainingQuantity"),
        @Json(name = "OnlyDisplayRemainingQuantityWhenStockIsLow") OnlyDisplayRemainingQuantityWhenStockIsLow("OnlyDisplayRemainingQuantityWhenStockIsLow"),
        @Json(name = "NeverDisplayRemainingQuantity") NeverDisplayRemainingQuantity("NeverDisplayRemainingQuantity");
    }

}

