/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ContactPoint

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param legalName 
 * @param businessName 
 * @param slogan 
 * @param homepage 
 * @param facebookPageUsername 
 * @param instagramUsername 
 * @param linkedInUsername 
 * @param twitterHandler 
 * @param gitHubUsername 
 * @param contactPoints 
 */


data class Organization (

    @Json(name = "legalName")
    val legalName: kotlin.String? = null,

    @Json(name = "businessName")
    val businessName: kotlin.String? = null,

    @Json(name = "slogan")
    val slogan: kotlin.String? = null,

    @Json(name = "homepage")
    val homepage: kotlin.String? = null,

    @Json(name = "facebookPageUsername")
    val facebookPageUsername: kotlin.String? = null,

    @Json(name = "instagramUsername")
    val instagramUsername: kotlin.String? = null,

    @Json(name = "linkedInUsername")
    val linkedInUsername: kotlin.String? = null,

    @Json(name = "twitterHandler")
    val twitterHandler: kotlin.String? = null,

    @Json(name = "gitHubUsername")
    val gitHubUsername: kotlin.String? = null,

    @Json(name = "contactPoints")
    val contactPoints: kotlin.collections.List<ContactPoint>? = null

) {


}

