/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.WalletWithdrawRequestCreateDto

class WalletWithdrawRequestCreateDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WalletWithdrawRequestCreateDto
        //val modelInstance = WalletWithdrawRequestCreateDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `timestamp`
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `requestedWithdrawAmount`
        should("test requestedWithdrawAmount") {
            // uncomment below to test the property
            //modelInstance.requestedWithdrawAmount shouldBe ("TODO")
        }

        // to test the property `currencyId`
        should("test currencyId") {
            // uncomment below to test the property
            //modelInstance.currencyId shouldBe ("TODO")
        }

        // to test the property `bankAccountId`
        should("test bankAccountId") {
            // uncomment below to test the property
            //modelInstance.bankAccountId shouldBe ("TODO")
        }

    }
}
