/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ServiceCaseTypesApi
import org.openapitools.client.models.Envelope
import org.openapitools.client.models.ErrorEnvelope
import org.openapitools.client.models.Int32Envelope
import org.openapitools.client.models.ServiceCaseTypeCreateDto
import org.openapitools.client.models.ServiceCaseTypeDtoEnvelope
import org.openapitools.client.models.ServiceCaseTypeDtoIReadOnlyListEnvelope
import org.openapitools.client.models.ServiceCaseTypeUpdateDto

class ServiceCaseTypesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ServiceCaseTypesApi
        //val apiInstance = ServiceCaseTypesApi()

        // to test createServiceCaseTypeAsync
        should("test createServiceCaseTypeAsync") {
            // uncomment below to test createServiceCaseTypeAsync
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val serviceCaseTypeCreateDto : ServiceCaseTypeCreateDto =  // ServiceCaseTypeCreateDto | 
            //val result : Envelope = apiInstance.createServiceCaseTypeAsync(tenantId, apiVersion, xApiVersion, serviceCaseTypeCreateDto)
            //result shouldBe ("TODO")
        }

        // to test deleteServiceCaseTypeAsync
        should("test deleteServiceCaseTypeAsync") {
            // uncomment below to test deleteServiceCaseTypeAsync
            //val serviceCaseTypeId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : Envelope = apiInstance.deleteServiceCaseTypeAsync(serviceCaseTypeId, tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test getServiceCaseTypeByIdAsync
        should("test getServiceCaseTypeByIdAsync") {
            // uncomment below to test getServiceCaseTypeByIdAsync
            //val serviceCaseTypeId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : ServiceCaseTypeDtoEnvelope = apiInstance.getServiceCaseTypeByIdAsync(serviceCaseTypeId, tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test getServiceCaseTypesAsync
        should("test getServiceCaseTypesAsync") {
            // uncomment below to test getServiceCaseTypesAsync
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : ServiceCaseTypeDtoIReadOnlyListEnvelope = apiInstance.getServiceCaseTypesAsync(tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test getServiceCaseTypesCountAsync
        should("test getServiceCaseTypesCountAsync") {
            // uncomment below to test getServiceCaseTypesCountAsync
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : Int32Envelope = apiInstance.getServiceCaseTypesCountAsync(tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test updateServiceCaseTypeAsync
        should("test updateServiceCaseTypeAsync") {
            // uncomment below to test updateServiceCaseTypeAsync
            //val serviceCaseTypeId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val serviceCaseTypeUpdateDto : ServiceCaseTypeUpdateDto =  // ServiceCaseTypeUpdateDto | 
            //val result : Envelope = apiInstance.updateServiceCaseTypeAsync(serviceCaseTypeId, tenantId, apiVersion, xApiVersion, serviceCaseTypeUpdateDto)
            //result shouldBe ("TODO")
        }

    }
}
