/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SuiteLicenseAssignmentDto

class SuiteLicenseAssignmentDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SuiteLicenseAssignmentDto
        //val modelInstance = SuiteLicenseAssignmentDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `timestamp`
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `assigned`
        should("test assigned") {
            // uncomment below to test the property
            //modelInstance.assigned shouldBe ("TODO")
        }

        // to test the property `enrollmentId`
        should("test enrollmentId") {
            // uncomment below to test the property
            //modelInstance.enrollmentId shouldBe ("TODO")
        }

        // to test the property `suiteLicenseId`
        should("test suiteLicenseId") {
            // uncomment below to test the property
            //modelInstance.suiteLicenseId shouldBe ("TODO")
        }

        // to test the property `expirationDate`
        should("test expirationDate") {
            // uncomment below to test the property
            //modelInstance.expirationDate shouldBe ("TODO")
        }

        // to test the property `availableSeats`
        should("test availableSeats") {
            // uncomment below to test the property
            //modelInstance.availableSeats shouldBe ("TODO")
        }

        // to test the property `totalSeats`
        should("test totalSeats") {
            // uncomment below to test the property
            //modelInstance.totalSeats shouldBe ("TODO")
        }

    }
}
