/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SuiteLicenseDto

class SuiteLicenseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SuiteLicenseDto
        //val modelInstance = SuiteLicenseDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `timestamp`
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `tenantId`
        should("test tenantId") {
            // uncomment below to test the property
            //modelInstance.tenantId shouldBe ("TODO")
        }

        // to test the property `licenseString`
        should("test licenseString") {
            // uncomment below to test the property
            //modelInstance.licenseString shouldBe ("TODO")
        }

        // to test the property `enrollmentId`
        should("test enrollmentId") {
            // uncomment below to test the property
            //modelInstance.enrollmentId shouldBe ("TODO")
        }

        // to test the property `expirationDate`
        should("test expirationDate") {
            // uncomment below to test the property
            //modelInstance.expirationDate shouldBe ("TODO")
        }

        // to test the property `availableSeats`
        should("test availableSeats") {
            // uncomment below to test the property
            //modelInstance.availableSeats shouldBe ("TODO")
        }

        // to test the property `totalSeats`
        should("test totalSeats") {
            // uncomment below to test the property
            //modelInstance.totalSeats shouldBe ("TODO")
        }

    }
}
