/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.SubscriptionsApi
import org.openapitools.client.models.Envelope
import org.openapitools.client.models.ErrorEnvelope
import org.openapitools.client.models.Int32Envelope
import org.openapitools.client.models.SubscriptionCreateDto
import org.openapitools.client.models.SubscriptionDtoEnvelope
import org.openapitools.client.models.SubscriptionDtoIReadOnlyListEnvelope
import org.openapitools.client.models.SubscriptionUpdateDto

class SubscriptionsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubscriptionsApi
        //val apiInstance = SubscriptionsApi()

        // to test createSubscriptionAsync
        should("test createSubscriptionAsync") {
            // uncomment below to test createSubscriptionAsync
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val subscriptionCreateDto : SubscriptionCreateDto =  // SubscriptionCreateDto | 
            //val result : Envelope = apiInstance.createSubscriptionAsync(tenantId, apiVersion, xApiVersion, subscriptionCreateDto)
            //result shouldBe ("TODO")
        }

        // to test deleteSubscriptionAsync
        should("test deleteSubscriptionAsync") {
            // uncomment below to test deleteSubscriptionAsync
            //val subscriptionId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : Envelope = apiInstance.deleteSubscriptionAsync(subscriptionId, tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test getSubscriptionByIdAsync
        should("test getSubscriptionByIdAsync") {
            // uncomment below to test getSubscriptionByIdAsync
            //val subscriptionId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : SubscriptionDtoEnvelope = apiInstance.getSubscriptionByIdAsync(subscriptionId, tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test getSubscriptionsAsync
        should("test getSubscriptionsAsync") {
            // uncomment below to test getSubscriptionsAsync
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : SubscriptionDtoIReadOnlyListEnvelope = apiInstance.getSubscriptionsAsync(tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test getSubscriptionsCountAsync
        should("test getSubscriptionsCountAsync") {
            // uncomment below to test getSubscriptionsCountAsync
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : Int32Envelope = apiInstance.getSubscriptionsCountAsync(tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test updateSubscriptionAsync
        should("test updateSubscriptionAsync") {
            // uncomment below to test updateSubscriptionAsync
            //val subscriptionId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val subscriptionUpdateDto : SubscriptionUpdateDto =  // SubscriptionUpdateDto | 
            //val result : Envelope = apiInstance.updateSubscriptionAsync(subscriptionId, tenantId, apiVersion, xApiVersion, subscriptionUpdateDto)
            //result shouldBe ("TODO")
        }

    }
}
