/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param pluralTitle 
 * @param singularTitle 
 * @param businessID 
 * @param itemCategoryID 
 * @param id 
 * @param timestamp 
 * @param description 
 * @param imageURL 
 * @param googleCategoryTaxonomy 
 * @param itemGoogleCategoryID 
 */


data class ItemTypeDto (

    @Json(name = "pluralTitle")
    val pluralTitle: kotlin.String,

    @Json(name = "singularTitle")
    val singularTitle: kotlin.String,

    @Json(name = "businessID")
    val businessID: kotlin.String,

    @Json(name = "itemCategoryID")
    val itemCategoryID: kotlin.String,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "imageURL")
    val imageURL: java.net.URI? = null,

    @Json(name = "googleCategoryTaxonomy")
    val googleCategoryTaxonomy: kotlin.String? = null,

    @Json(name = "itemGoogleCategoryID")
    val itemGoogleCategoryID: kotlin.String? = null

) {


}

