/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param timestamp 
 * @param tenantId 
 * @param enrollmentId 
 * @param itemId 
 * @param isItemMozaicBG 
 * @param mD5Hash 
 * @param metadata 
 * @param fileUploadURL 
 * @param fileName 
 * @param title 
 * @param `abstract` 
 * @param author 
 * @param keyWords 
 * @param notes 
 * @param contentType 
 * @param fileLength 
 * @param validResponse 
 * @param socialProfileId 
 * @param parentFileUploadId 
 * @param userId 
 */


data class ItemImageDto (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime? = null,

    @Json(name = "tenantId")
    val tenantId: kotlin.String? = null,

    @Json(name = "enrollmentId")
    val enrollmentId: kotlin.String? = null,

    @Json(name = "itemId")
    val itemId: kotlin.String? = null,

    @Json(name = "isItemMozaicBG")
    val isItemMozaicBG: kotlin.Boolean? = null,

    @Json(name = "mD5Hash")
    val mD5Hash: kotlin.String? = null,

    @Json(name = "metadata")
    val metadata: kotlin.String? = null,

    @Json(name = "fileUploadURL")
    val fileUploadURL: kotlin.String? = null,

    @Json(name = "fileName")
    val fileName: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "abstract")
    val `abstract`: kotlin.String? = null,

    @Json(name = "author")
    val author: kotlin.String? = null,

    @Json(name = "keyWords")
    val keyWords: kotlin.String? = null,

    @Json(name = "notes")
    val notes: kotlin.String? = null,

    @Json(name = "contentType")
    val contentType: kotlin.String? = null,

    @Json(name = "fileLength")
    val fileLength: kotlin.Long? = null,

    @Json(name = "validResponse")
    val validResponse: kotlin.Boolean? = null,

    @Json(name = "socialProfileId")
    val socialProfileId: kotlin.String? = null,

    @Json(name = "parentFileUploadId")
    val parentFileUploadId: kotlin.String? = null,

    @Json(name = "userId")
    val userId: kotlin.String? = null

) {


}

