/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ShipmentDto

class ShipmentDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ShipmentDto
        //val modelInstance = ShipmentDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `trackingCode`
        should("test trackingCode") {
            // uncomment below to test the property
            //modelInstance.trackingCode shouldBe ("TODO")
        }

        // to test the property `isInternational`
        should("test isInternational") {
            // uncomment below to test the property
            //modelInstance.isInternational shouldBe ("TODO")
        }

        // to test the property `shipmentTimestamp`
        should("test shipmentTimestamp") {
            // uncomment below to test the property
            //modelInstance.shipmentTimestamp shouldBe ("TODO")
        }

        // to test the property `deliveryTimestamp`
        should("test deliveryTimestamp") {
            // uncomment below to test the property
            //modelInstance.deliveryTimestamp shouldBe ("TODO")
        }

        // to test the property `expectedShippingDate`
        should("test expectedShippingDate") {
            // uncomment below to test the property
            //modelInstance.expectedShippingDate shouldBe ("TODO")
        }

        // to test the property `expectedDeliveryDate`
        should("test expectedDeliveryDate") {
            // uncomment below to test the property
            //modelInstance.expectedDeliveryDate shouldBe ("TODO")
        }

    }
}
