/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SkipTokenQueryOption
import org.openapitools.client.models.ODataQueryContext

class SkipTokenQueryOptionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SkipTokenQueryOption
        //val modelInstance = SkipTokenQueryOption()

        // to test the property `rawValue`
        should("test rawValue") {
            // uncomment below to test the property
            //modelInstance.rawValue shouldBe ("TODO")
        }

        // to test the property `context`
        should("test context") {
            // uncomment below to test the property
            //modelInstance.context shouldBe ("TODO")
        }

        // to test the property `validator`
        should("test validator") {
            // uncomment below to test the property
            //modelInstance.validator shouldBe ("TODO")
        }

        // to test the property `handler`
        should("test handler") {
            // uncomment below to test the property
            //modelInstance.handler shouldBe ("TODO")
        }

    }
}
