/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import org.openapitools.client.models.ErrorEnvelope
import org.openapitools.client.models.TaskTypeCreateDto
import org.openapitools.client.models.TaskTypeDto
import org.openapitools.client.models.TaskTypeUpdateDto

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class TaskTypesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://absuite.net")
        }
    }

    /**
     * Creates a new task type
     * Creates a new task type for the current tenant.
     * @param tenantId 
     * @param taskTypeCreateDto  (optional)
     * @return TaskTypeDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createTaskTypeAsync(tenantId: java.util.UUID, taskTypeCreateDto: TaskTypeCreateDto? = null) : TaskTypeDto {
        val localVarResponse = createTaskTypeAsyncWithHttpInfo(tenantId = tenantId, taskTypeCreateDto = taskTypeCreateDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TaskTypeDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Creates a new task type
     * Creates a new task type for the current tenant.
     * @param tenantId 
     * @param taskTypeCreateDto  (optional)
     * @return ApiResponse<TaskTypeDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createTaskTypeAsyncWithHttpInfo(tenantId: java.util.UUID, taskTypeCreateDto: TaskTypeCreateDto?) : ApiResponse<TaskTypeDto?> {
        val localVariableConfig = createTaskTypeAsyncRequestConfig(tenantId = tenantId, taskTypeCreateDto = taskTypeCreateDto)

        return request<TaskTypeCreateDto, TaskTypeDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createTaskTypeAsync
     *
     * @param tenantId 
     * @param taskTypeCreateDto  (optional)
     * @return RequestConfig
     */
    fun createTaskTypeAsyncRequestConfig(tenantId: java.util.UUID, taskTypeCreateDto: TaskTypeCreateDto?) : RequestConfig<TaskTypeCreateDto> {
        val localVariableBody = taskTypeCreateDto
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("tenantId", listOf(tenantId.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v2/ProjectsService/TaskTypes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Deletes a task type
     * Deletes the specified task type.
     * @param taskTypeId 
     * @param tenantId 
     * @return TaskTypeDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteTaskTypeAsync(taskTypeId: java.util.UUID, tenantId: java.util.UUID) : TaskTypeDto {
        val localVarResponse = deleteTaskTypeAsyncWithHttpInfo(taskTypeId = taskTypeId, tenantId = tenantId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TaskTypeDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Deletes a task type
     * Deletes the specified task type.
     * @param taskTypeId 
     * @param tenantId 
     * @return ApiResponse<TaskTypeDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteTaskTypeAsyncWithHttpInfo(taskTypeId: java.util.UUID, tenantId: java.util.UUID) : ApiResponse<TaskTypeDto?> {
        val localVariableConfig = deleteTaskTypeAsyncRequestConfig(taskTypeId = taskTypeId, tenantId = tenantId)

        return request<Unit, TaskTypeDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteTaskTypeAsync
     *
     * @param taskTypeId 
     * @param tenantId 
     * @return RequestConfig
     */
    fun deleteTaskTypeAsyncRequestConfig(taskTypeId: java.util.UUID, tenantId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("tenantId", listOf(tenantId.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/v2/ProjectsService/TaskTypes/{taskTypeId}".replace("{"+"taskTypeId"+"}", encodeURIComponent(taskTypeId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Gets a task type by ID
     * Retrieves the details of a task type using its unique identifier.
     * @param taskTypeId 
     * @param tenantId 
     * @return TaskTypeDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getTaskTypeByIdAsync(taskTypeId: java.util.UUID, tenantId: java.util.UUID) : TaskTypeDto {
        val localVarResponse = getTaskTypeByIdAsyncWithHttpInfo(taskTypeId = taskTypeId, tenantId = tenantId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TaskTypeDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Gets a task type by ID
     * Retrieves the details of a task type using its unique identifier.
     * @param taskTypeId 
     * @param tenantId 
     * @return ApiResponse<TaskTypeDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getTaskTypeByIdAsyncWithHttpInfo(taskTypeId: java.util.UUID, tenantId: java.util.UUID) : ApiResponse<TaskTypeDto?> {
        val localVariableConfig = getTaskTypeByIdAsyncRequestConfig(taskTypeId = taskTypeId, tenantId = tenantId)

        return request<Unit, TaskTypeDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getTaskTypeByIdAsync
     *
     * @param taskTypeId 
     * @param tenantId 
     * @return RequestConfig
     */
    fun getTaskTypeByIdAsyncRequestConfig(taskTypeId: java.util.UUID, tenantId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("tenantId", listOf(tenantId.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v2/ProjectsService/TaskTypes/{taskTypeId}".replace("{"+"taskTypeId"+"}", encodeURIComponent(taskTypeId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Updates a task type
     * Updates the specified task type.
     * @param taskTypeId 
     * @param tenantId 
     * @param taskTypeUpdateDto  (optional)
     * @return TaskTypeDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateTaskTypeAsync(taskTypeId: java.util.UUID, tenantId: java.util.UUID, taskTypeUpdateDto: TaskTypeUpdateDto? = null) : TaskTypeDto {
        val localVarResponse = updateTaskTypeAsyncWithHttpInfo(taskTypeId = taskTypeId, tenantId = tenantId, taskTypeUpdateDto = taskTypeUpdateDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TaskTypeDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Updates a task type
     * Updates the specified task type.
     * @param taskTypeId 
     * @param tenantId 
     * @param taskTypeUpdateDto  (optional)
     * @return ApiResponse<TaskTypeDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateTaskTypeAsyncWithHttpInfo(taskTypeId: java.util.UUID, tenantId: java.util.UUID, taskTypeUpdateDto: TaskTypeUpdateDto?) : ApiResponse<TaskTypeDto?> {
        val localVariableConfig = updateTaskTypeAsyncRequestConfig(taskTypeId = taskTypeId, tenantId = tenantId, taskTypeUpdateDto = taskTypeUpdateDto)

        return request<TaskTypeUpdateDto, TaskTypeDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateTaskTypeAsync
     *
     * @param taskTypeId 
     * @param tenantId 
     * @param taskTypeUpdateDto  (optional)
     * @return RequestConfig
     */
    fun updateTaskTypeAsyncRequestConfig(taskTypeId: java.util.UUID, tenantId: java.util.UUID, taskTypeUpdateDto: TaskTypeUpdateDto?) : RequestConfig<TaskTypeUpdateDto> {
        val localVariableBody = taskTypeUpdateDto
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("tenantId", listOf(tenantId.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/api/v2/ProjectsService/TaskTypes/{taskTypeId}".replace("{"+"taskTypeId"+"}", encodeURIComponent(taskTypeId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
