/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param taxId 
 * @param phone 
 * @param email 
 * @param address 
 * @param postalCode 
 * @param businessName 
 * @param commercialName 
 * @param countryId 
 * @param stateId 
 * @param cityId 
 * @param fiscalIdentificationTypeId 
 * @param fiscalAuthorityId 
 * @param fiscalRegimeId 
 * @param id 
 * @param timestamp 
 * @param contactId 
 * @param tenantId 
 * @param address1 
 * @param address2 
 * @param ticker 
 * @param duns 
 * @param isPublicCompany 
 * @param isFactaCustomer 
 */


data class BillingProfileCreateDto (

    @Json(name = "taxId")
    val taxId: kotlin.String,

    @Json(name = "phone")
    val phone: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "postalCode")
    val postalCode: kotlin.String,

    @Json(name = "businessName")
    val businessName: kotlin.String,

    @Json(name = "commercialName")
    val commercialName: kotlin.String,

    @Json(name = "countryId")
    val countryId: kotlin.String,

    @Json(name = "stateId")
    val stateId: kotlin.String,

    @Json(name = "cityId")
    val cityId: kotlin.String,

    @Json(name = "fiscalIdentificationTypeId")
    val fiscalIdentificationTypeId: kotlin.String,

    @Json(name = "fiscalAuthorityId")
    val fiscalAuthorityId: kotlin.String,

    @Json(name = "fiscalRegimeId")
    val fiscalRegimeId: kotlin.String,

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime? = null,

    @Json(name = "contactId")
    val contactId: kotlin.String? = null,

    @Json(name = "tenantId")
    val tenantId: kotlin.String? = null,

    @Json(name = "address1")
    val address1: kotlin.String? = null,

    @Json(name = "address2")
    val address2: kotlin.String? = null,

    @Json(name = "ticker")
    val ticker: kotlin.String? = null,

    @Json(name = "duns")
    val duns: kotlin.String? = null,

    @Json(name = "isPublicCompany")
    val isPublicCompany: kotlin.Boolean? = null,

    @Json(name = "isFactaCustomer")
    val isFactaCustomer: kotlin.Boolean? = null

) {


}

