/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param fromDate 
 * @param toDate 
 * @param tenantId 
 * @param enrollmentId 
 * @param fiscalYearId 
 */


data class FiscalPeriodUpdateDto (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "fromDate")
    val fromDate: java.time.OffsetDateTime? = null,

    @Json(name = "toDate")
    val toDate: java.time.OffsetDateTime? = null,

    @Json(name = "tenantId")
    val tenantId: kotlin.String? = null,

    @Json(name = "enrollmentId")
    val enrollmentId: kotlin.String? = null,

    @Json(name = "fiscalYearId")
    val fiscalYearId: kotlin.String? = null

) {


}

