/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.BudgetAccountEntryCreateDto

class BudgetAccountEntryCreateDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BudgetAccountEntryCreateDto
        //val modelInstance = BudgetAccountEntryCreateDto()

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `currencyId`
        should("test currencyId") {
            // uncomment below to test the property
            //modelInstance.currencyId shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `timestamp`
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `tenantId`
        should("test tenantId") {
            // uncomment below to test the property
            //modelInstance.tenantId shouldBe ("TODO")
        }

        // to test the property `enrollmentId`
        should("test enrollmentId") {
            // uncomment below to test the property
            //modelInstance.enrollmentId shouldBe ("TODO")
        }

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `debitAccountId`
        should("test debitAccountId") {
            // uncomment below to test the property
            //modelInstance.debitAccountId shouldBe ("TODO")
        }

        // to test the property `creditAccountId`
        should("test creditAccountId") {
            // uncomment below to test the property
            //modelInstance.creditAccountId shouldBe ("TODO")
        }

        // to test the property `journalEntryId`
        should("test journalEntryId") {
            // uncomment below to test the property
            //modelInstance.journalEntryId shouldBe ("TODO")
        }

        // to test the property `accountingEntryType`
        should("test accountingEntryType") {
            // uncomment below to test the property
            //modelInstance.accountingEntryType shouldBe ("TODO")
        }

        // to test the property `budgetId`
        should("test budgetId") {
            // uncomment below to test the property
            //modelInstance.budgetId shouldBe ("TODO")
        }

    }
}
