/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GrantUpdateDto

class GrantUpdateDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GrantUpdateDto
        //val modelInstance = GrantUpdateDto()

        // to test the property `tenantId`
        should("test tenantId") {
            // uncomment below to test the property
            //modelInstance.tenantId shouldBe ("TODO")
        }

        // to test the property `enrollmentId`
        should("test enrollmentId") {
            // uncomment below to test the property
            //modelInstance.enrollmentId shouldBe ("TODO")
        }

    }
}
