/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param itemId 
 * @param itemPackingSlipId 
 * @param quantity 
 * @param id 
 * @param timestamp 
 */


data class ItemPackingSlipEntryCreateDto (

    @Json(name = "itemId")
    val itemId: kotlin.String,

    @Json(name = "itemPackingSlipId")
    val itemPackingSlipId: kotlin.String,

    @Json(name = "quantity")
    val quantity: kotlin.String,

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime? = null

) {


}

