/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ItemRefundPoliciesApi
import org.openapitools.client.models.ErrorEnvelope
import org.openapitools.client.models.Int32Envelope
import org.openapitools.client.models.ItemRefundPolicyDtoEnvelope
import org.openapitools.client.models.ItemRefundPolicyDtoListEnvelope

class ItemRefundPoliciesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ItemRefundPoliciesApi
        //val apiInstance = ItemRefundPoliciesApi()

        // to test countItemRefundPoliciesAsync
        should("test countItemRefundPoliciesAsync") {
            // uncomment below to test countItemRefundPoliciesAsync
            //val itemId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : Int32Envelope = apiInstance.countItemRefundPoliciesAsync(itemId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test getItemRefundPoliciesAsync
        should("test getItemRefundPoliciesAsync") {
            // uncomment below to test getItemRefundPoliciesAsync
            //val itemId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : ItemRefundPolicyDtoListEnvelope = apiInstance.getItemRefundPoliciesAsync(itemId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test getItemRefundPolicyByIdAsync
        should("test getItemRefundPolicyByIdAsync") {
            // uncomment below to test getItemRefundPolicyByIdAsync
            //val itemRefundPolicyId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val itemId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : ItemRefundPolicyDtoEnvelope = apiInstance.getItemRefundPolicyByIdAsync(itemRefundPolicyId, itemId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test relateItemToRefundPolicyAsync
        should("test relateItemToRefundPolicyAsync") {
            // uncomment below to test relateItemToRefundPolicyAsync
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val itemId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val refundPolicyId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //apiInstance.relateItemToRefundPolicyAsync(tenantId, itemId, refundPolicyId, apiVersion, xApiVersion)
        }

        // to test removeRefundPolicyFromItemAsync
        should("test removeRefundPolicyFromItemAsync") {
            // uncomment below to test removeRefundPolicyFromItemAsync
            //val itemRefundPolicyId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val itemId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //apiInstance.removeRefundPolicyFromItemAsync(itemRefundPolicyId, tenantId, itemId, apiVersion, xApiVersion)
        }

    }
}
