/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param timestamp 
 * @param title 
 * @param description 
 * @param supportTicketStatus 
 * @param userId 
 * @param contactId 
 * @param tenantId 
 * @param enrollmentId 
 * @param supportTicketTypeId 
 * @param supportEntitlementId 
 * @param supportPriorityId 
 */


data class SupportTicketDto (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "supportTicketStatus")
    val supportTicketStatus: SupportTicketDto.SupportTicketStatus? = null,

    @Json(name = "userId")
    val userId: kotlin.String? = null,

    @Json(name = "contactId")
    val contactId: kotlin.String? = null,

    @Json(name = "tenantId")
    val tenantId: kotlin.String? = null,

    @Json(name = "enrollmentId")
    val enrollmentId: kotlin.String? = null,

    @Json(name = "supportTicketTypeId")
    val supportTicketTypeId: kotlin.String? = null,

    @Json(name = "supportEntitlementId")
    val supportEntitlementId: kotlin.String? = null,

    @Json(name = "supportPriorityId")
    val supportPriorityId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: New,OpenAndWaitingForAgent,OpenAndWaitingForCustomer,Closed
     */
    @JsonClass(generateAdapter = false)
    enum class SupportTicketStatus(val value: kotlin.String) {
        @Json(name = "New") New("New"),
        @Json(name = "OpenAndWaitingForAgent") OpenAndWaitingForAgent("OpenAndWaitingForAgent"),
        @Json(name = "OpenAndWaitingForCustomer") OpenAndWaitingForCustomer("OpenAndWaitingForCustomer"),
        @Json(name = "Closed") Closed("Closed");
    }

}

