/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param title 
 * @param courseId 
 * @param id 
 * @param timestamp 
 * @param description 
 * @param overallScore 
 * @param courseUnitId 
 * @param courseGradingRubricId 
 * @param releaseDateTime 
 */


data class CourseProblemSetCreateDto (

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "courseId")
    val courseId: kotlin.String,

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "overallScore")
    val overallScore: kotlin.Double? = null,

    @Json(name = "courseUnitId")
    val courseUnitId: kotlin.String? = null,

    @Json(name = "courseGradingRubricId")
    val courseGradingRubricId: kotlin.String? = null,

    @Json(name = "releaseDateTime")
    val releaseDateTime: java.time.OffsetDateTime? = null

) {


}

