/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ExecutionContext
import org.openapitools.client.models.AuthResult
import org.openapitools.client.models.CartDto
import org.openapitools.client.models.CountryDto
import org.openapitools.client.models.CrmContext
import org.openapitools.client.models.CurrencyDto
import org.openapitools.client.models.ExtendedInviteDto
import org.openapitools.client.models.ExtendedTenantDto
import org.openapitools.client.models.ExtendedTenantEnrollmentDto
import org.openapitools.client.models.ExtendedUserDto
import org.openapitools.client.models.ForexRatesDto
import org.openapitools.client.models.Money
import org.openapitools.client.models.SuiteLicenseFeatureDto
import org.openapitools.client.models.TenantDto
import org.openapitools.client.models.TenantEnrollmentDto
import org.openapitools.client.models.WebPortalDto

class ExecutionContextTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExecutionContext
        //val modelInstance = ExecutionContext()

        // to test the property `isAuthenticated`
        should("test isAuthenticated") {
            // uncomment below to test the property
            //modelInstance.isAuthenticated shouldBe ("TODO")
        }

        // to test the property `currentCartId`
        should("test currentCartId") {
            // uncomment below to test the property
            //modelInstance.currentCartId shouldBe ("TODO")
        }

        // to test the property `currentUserId`
        should("test currentUserId") {
            // uncomment below to test the property
            //modelInstance.currentUserId shouldBe ("TODO")
        }

        // to test the property `currentTenantId`
        should("test currentTenantId") {
            // uncomment below to test the property
            //modelInstance.currentTenantId shouldBe ("TODO")
        }

        // to test the property `currentPortalId`
        should("test currentPortalId") {
            // uncomment below to test the property
            //modelInstance.currentPortalId shouldBe ("TODO")
        }

        // to test the property `currentEnrollmentId`
        should("test currentEnrollmentId") {
            // uncomment below to test the property
            //modelInstance.currentEnrollmentId shouldBe ("TODO")
        }

        // to test the property `currencyId`
        should("test currencyId") {
            // uncomment below to test the property
            //modelInstance.currencyId shouldBe ("TODO")
        }

        // to test the property `pageSize`
        should("test pageSize") {
            // uncomment below to test the property
            //modelInstance.pageSize shouldBe ("TODO")
        }

        // to test the property `dateFormat`
        should("test dateFormat") {
            // uncomment below to test the property
            //modelInstance.dateFormat shouldBe ("TODO")
        }

        // to test the property `currencyFormat`
        should("test currencyFormat") {
            // uncomment below to test the property
            //modelInstance.currencyFormat shouldBe ("TODO")
        }

        // to test the property `dateTimeFormat`
        should("test dateTimeFormat") {
            // uncomment below to test the property
            //modelInstance.dateTimeFormat shouldBe ("TODO")
        }

        // to test the property `toDateDataSummaries`
        should("test toDateDataSummaries") {
            // uncomment below to test the property
            //modelInstance.toDateDataSummaries shouldBe ("TODO")
        }

        // to test the property `fromDateDataSummaries`
        should("test fromDateDataSummaries") {
            // uncomment below to test the property
            //modelInstance.fromDateDataSummaries shouldBe ("TODO")
        }

        // to test the property `authorization`
        should("test authorization") {
            // uncomment below to test the property
            //modelInstance.authorization shouldBe ("TODO")
        }

        // to test the property `user`
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `currentTenant`
        should("test currentTenant") {
            // uncomment below to test the property
            //modelInstance.currentTenant shouldBe ("TODO")
        }

        // to test the property `currentEnrollment`
        should("test currentEnrollment") {
            // uncomment below to test the property
            //modelInstance.currentEnrollment shouldBe ("TODO")
        }

        // to test the property `selectedTenantMappings`
        should("test selectedTenantMappings") {
            // uncomment below to test the property
            //modelInstance.selectedTenantMappings shouldBe ("TODO")
        }

        // to test the property `portalOwnerMappings`
        should("test portalOwnerMappings") {
            // uncomment below to test the property
            //modelInstance.portalOwnerMappings shouldBe ("TODO")
        }

        // to test the property `rootTenantMappings`
        should("test rootTenantMappings") {
            // uncomment below to test the property
            //modelInstance.rootTenantMappings shouldBe ("TODO")
        }

        // to test the property `cart`
        should("test cart") {
            // uncomment below to test the property
            //modelInstance.cart shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `forexRates`
        should("test forexRates") {
            // uncomment below to test the property
            //modelInstance.forexRates shouldBe ("TODO")
        }

        // to test the property `exchangeRate`
        should("test exchangeRate") {
            // uncomment below to test the property
            //modelInstance.exchangeRate shouldBe ("TODO")
        }

        // to test the property `country`
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `rootTenant`
        should("test rootTenant") {
            // uncomment below to test the property
            //modelInstance.rootTenant shouldBe ("TODO")
        }

        // to test the property `currentPortal`
        should("test currentPortal") {
            // uncomment below to test the property
            //modelInstance.currentPortal shouldBe ("TODO")
        }

        // to test the property `tenants`
        should("test tenants") {
            // uncomment below to test the property
            //modelInstance.tenants shouldBe ("TODO")
        }

        // to test the property `enrollments`
        should("test enrollments") {
            // uncomment below to test the property
            //modelInstance.enrollments shouldBe ("TODO")
        }

        // to test the property `availablePortals`
        should("test availablePortals") {
            // uncomment below to test the property
            //modelInstance.availablePortals shouldBe ("TODO")
        }

        // to test the property `invitations`
        should("test invitations") {
            // uncomment below to test the property
            //modelInstance.invitations shouldBe ("TODO")
        }

        // to test the property `grantedPermissions`
        should("test grantedPermissions") {
            // uncomment below to test the property
            //modelInstance.grantedPermissions shouldBe ("TODO")
        }

        // to test the property `accessibleFeatures`
        should("test accessibleFeatures") {
            // uncomment below to test the property
            //modelInstance.accessibleFeatures shouldBe ("TODO")
        }

        // to test the property `cultureName`
        should("test cultureName") {
            // uncomment below to test the property
            //modelInstance.cultureName shouldBe ("TODO")
        }

        // to test the property `timezoneId`
        should("test timezoneId") {
            // uncomment below to test the property
            //modelInstance.timezoneId shouldBe ("TODO")
        }

    }
}
