/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PrivacyOptions

class PrivacyOptionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PrivacyOptions
        //val modelInstance = PrivacyOptions()

        // to test the property `cookiesNoticeMessage`
        should("test cookiesNoticeMessage") {
            // uncomment below to test the property
            //modelInstance.cookiesNoticeMessage shouldBe ("TODO")
        }

    }
}
