/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param test 
 * @param ip 
 * @param bank 
 * @param status 
 * @param errors 
 * @param response 
 * @param authCode 
 * @param paymentID 
 * @param franchise 
 * @param signature 
 * @param paymentStatus 
 */


data class PaymentResponse (

    @Json(name = "test")
    val test: kotlin.Boolean? = null,

    @Json(name = "ip")
    val ip: kotlin.String? = null,

    @Json(name = "bank")
    val bank: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "errors")
    val errors: kotlin.Any? = null,

    @Json(name = "response")
    val response: kotlin.String? = null,

    @Json(name = "authCode")
    val authCode: kotlin.String? = null,

    @Json(name = "paymentID")
    val paymentID: kotlin.String? = null,

    @Json(name = "franchise")
    val franchise: kotlin.String? = null,

    @Json(name = "signature")
    val signature: kotlin.String? = null,

    @Json(name = "paymentStatus")
    val paymentStatus: PaymentResponse.PaymentStatus? = null

) {

    /**
     * 
     *
     * Values: _0,_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11
     */
    @JsonClass(generateAdapter = false)
    enum class PaymentStatus(val value: kotlin.Int) {
        @Json(name = "0") _0(0),
        @Json(name = "1") _1(1),
        @Json(name = "2") _2(2),
        @Json(name = "3") _3(3),
        @Json(name = "4") _4(4),
        @Json(name = "5") _5(5),
        @Json(name = "6") _6(6),
        @Json(name = "7") _7(7),
        @Json(name = "8") _8(8),
        @Json(name = "9") _9(9),
        @Json(name = "10") _10(10),
        @Json(name = "11") _11(11);
    }

}

