/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.WorkOrdersApi
import org.openapitools.client.models.EmptyEnvelope
import org.openapitools.client.models.ErrorEnvelope
import org.openapitools.client.models.Int32Envelope
import org.openapitools.client.models.Operation
import org.openapitools.client.models.WorkOrderCreateDto
import org.openapitools.client.models.WorkOrderDto
import org.openapitools.client.models.WorkOrderDtoListEnvelope
import org.openapitools.client.models.WorkOrderUpdateDto

class WorkOrdersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WorkOrdersApi
        //val apiInstance = WorkOrdersApi()

        // to test createWorkOrderAsync
        should("test createWorkOrderAsync") {
            // uncomment below to test createWorkOrderAsync
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val workOrderCreateDto : WorkOrderCreateDto =  // WorkOrderCreateDto | 
            //apiInstance.createWorkOrderAsync(tenantId, apiVersion, xApiVersion, workOrderCreateDto)
        }

        // to test deleteWorkOrderAsync
        should("test deleteWorkOrderAsync") {
            // uncomment below to test deleteWorkOrderAsync
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //apiInstance.deleteWorkOrderAsync(id, tenantId, apiVersion, xApiVersion)
        }

        // to test getWorkOrderByIdAsync
        should("test getWorkOrderByIdAsync") {
            // uncomment below to test getWorkOrderByIdAsync
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : WorkOrderDto = apiInstance.getWorkOrderByIdAsync(id, tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test getWorkOrdersAsync
        should("test getWorkOrdersAsync") {
            // uncomment below to test getWorkOrdersAsync
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : WorkOrderDtoListEnvelope = apiInstance.getWorkOrdersAsync(tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test getWorkOrdersCountAsync
        should("test getWorkOrdersCountAsync") {
            // uncomment below to test getWorkOrdersCountAsync
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : Int32Envelope = apiInstance.getWorkOrdersCountAsync(tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test patchWorkOrderAsync
        should("test patchWorkOrderAsync") {
            // uncomment below to test patchWorkOrderAsync
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val operation : kotlin.collections.List<Operation> =  // kotlin.collections.List<Operation> | 
            //val result : EmptyEnvelope = apiInstance.patchWorkOrderAsync(id, tenantId, apiVersion, xApiVersion, operation)
            //result shouldBe ("TODO")
        }

        // to test updateWorkOrderAsync
        should("test updateWorkOrderAsync") {
            // uncomment below to test updateWorkOrderAsync
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val workOrderUpdateDto : WorkOrderUpdateDto =  // WorkOrderUpdateDto | 
            //apiInstance.updateWorkOrderAsync(id, tenantId, apiVersion, xApiVersion, workOrderUpdateDto)
        }

    }
}
