/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RailWaybillUpdateDto

class RailWaybillUpdateDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RailWaybillUpdateDto
        //val modelInstance = RailWaybillUpdateDto()

        // to test the property `documentNumber`
        should("test documentNumber") {
            // uncomment below to test the property
            //modelInstance.documentNumber shouldBe ("TODO")
        }

        // to test the property `shipperContactId`
        should("test shipperContactId") {
            // uncomment below to test the property
            //modelInstance.shipperContactId shouldBe ("TODO")
        }

        // to test the property `consigneeContactId`
        should("test consigneeContactId") {
            // uncomment below to test the property
            //modelInstance.consigneeContactId shouldBe ("TODO")
        }

        // to test the property `carrierId`
        should("test carrierId") {
            // uncomment below to test the property
            //modelInstance.carrierId shouldBe ("TODO")
        }

        // to test the property `railOperatorName`
        should("test railOperatorName") {
            // uncomment below to test the property
            //modelInstance.railOperatorName shouldBe ("TODO")
        }

        // to test the property `stationOfDeparture`
        should("test stationOfDeparture") {
            // uncomment below to test the property
            //modelInstance.stationOfDeparture shouldBe ("TODO")
        }

        // to test the property `stationOfDepartureCode`
        should("test stationOfDepartureCode") {
            // uncomment below to test the property
            //modelInstance.stationOfDepartureCode shouldBe ("TODO")
        }

        // to test the property `stationOfDestination`
        should("test stationOfDestination") {
            // uncomment below to test the property
            //modelInstance.stationOfDestination shouldBe ("TODO")
        }

        // to test the property `stationOfDestinationCode`
        should("test stationOfDestinationCode") {
            // uncomment below to test the property
            //modelInstance.stationOfDestinationCode shouldBe ("TODO")
        }

        // to test the property `prescribedRoute`
        should("test prescribedRoute") {
            // uncomment below to test the property
            //modelInstance.prescribedRoute shouldBe ("TODO")
        }

        // to test the property `wagonNumbers`
        should("test wagonNumbers") {
            // uncomment below to test the property
            //modelInstance.wagonNumbers shouldBe ("TODO")
        }

        // to test the property `dateOfAcceptance`
        should("test dateOfAcceptance") {
            // uncomment below to test the property
            //modelInstance.dateOfAcceptance shouldBe ("TODO")
        }

        // to test the property `dateOfDelivery`
        should("test dateOfDelivery") {
            // uncomment below to test the property
            //modelInstance.dateOfDelivery shouldBe ("TODO")
        }

        // to test the property `freightTerms`
        should("test freightTerms") {
            // uncomment below to test the property
            //modelInstance.freightTerms shouldBe ("TODO")
        }

        // to test the property `freightAmount`
        should("test freightAmount") {
            // uncomment below to test the property
            //modelInstance.freightAmount shouldBe ("TODO")
        }

        // to test the property `freightCurrencyId`
        should("test freightCurrencyId") {
            // uncomment below to test the property
            //modelInstance.freightCurrencyId shouldBe ("TODO")
        }

        // to test the property `totalGrossWeightKg`
        should("test totalGrossWeightKg") {
            // uncomment below to test the property
            //modelInstance.totalGrossWeightKg shouldBe ("TODO")
        }

        // to test the property `totalPackages`
        should("test totalPackages") {
            // uncomment below to test the property
            //modelInstance.totalPackages shouldBe ("TODO")
        }

        // to test the property `totalVolumeM3`
        should("test totalVolumeM3") {
            // uncomment below to test the property
            //modelInstance.totalVolumeM3 shouldBe ("TODO")
        }

        // to test the property `customsFormalities`
        should("test customsFormalities") {
            // uncomment below to test the property
            //modelInstance.customsFormalities shouldBe ("TODO")
        }

        // to test the property `specialInstructions`
        should("test specialInstructions") {
            // uncomment below to test the property
            //modelInstance.specialInstructions shouldBe ("TODO")
        }

        // to test the property `remarks`
        should("test remarks") {
            // uncomment below to test the property
            //modelInstance.remarks shouldBe ("TODO")
        }

        // to test the property `shipmentId`
        should("test shipmentId") {
            // uncomment below to test the property
            //modelInstance.shipmentId shouldBe ("TODO")
        }

    }
}
