/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.BlogPostCategoriesApi
import org.openapitools.client.models.BlogPostCategoryCreateDto
import org.openapitools.client.models.BlogPostCategoryDtoEnvelope
import org.openapitools.client.models.BlogPostCategoryDtoListEnvelope
import org.openapitools.client.models.BlogPostCategoryUpdateDto
import org.openapitools.client.models.EmptyEnvelope
import org.openapitools.client.models.ErrorEnvelope
import org.openapitools.client.models.Int32Envelope

class BlogPostCategoriesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BlogPostCategoriesApi
        //val apiInstance = BlogPostCategoriesApi()

        // to test countBlogPostCategoriesAsync
        should("test countBlogPostCategoriesAsync") {
            // uncomment below to test countBlogPostCategoriesAsync
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : Int32Envelope = apiInstance.countBlogPostCategoriesAsync(tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test createBlogPostCategoryAsync
        should("test createBlogPostCategoryAsync") {
            // uncomment below to test createBlogPostCategoryAsync
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val blogPostCategoryCreateDto : BlogPostCategoryCreateDto =  // BlogPostCategoryCreateDto | 
            //val result : EmptyEnvelope = apiInstance.createBlogPostCategoryAsync(tenantId, apiVersion, xApiVersion, blogPostCategoryCreateDto)
            //result shouldBe ("TODO")
        }

        // to test deleteBlogPostCategoryAsync
        should("test deleteBlogPostCategoryAsync") {
            // uncomment below to test deleteBlogPostCategoryAsync
            //val blogPostCategoryId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : EmptyEnvelope = apiInstance.deleteBlogPostCategoryAsync(blogPostCategoryId, tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test getBlogPostCategoriesAsync
        should("test getBlogPostCategoriesAsync") {
            // uncomment below to test getBlogPostCategoriesAsync
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : BlogPostCategoryDtoListEnvelope = apiInstance.getBlogPostCategoriesAsync(tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test getBlogPostCategoryByIdAsync
        should("test getBlogPostCategoryByIdAsync") {
            // uncomment below to test getBlogPostCategoryByIdAsync
            //val blogPostCategoryId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val result : BlogPostCategoryDtoEnvelope = apiInstance.getBlogPostCategoryByIdAsync(blogPostCategoryId, tenantId, apiVersion, xApiVersion)
            //result shouldBe ("TODO")
        }

        // to test updateBlogPostCategoryAsync
        should("test updateBlogPostCategoryAsync") {
            // uncomment below to test updateBlogPostCategoryAsync
            //val blogPostCategoryId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tenantId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val apiVersion : kotlin.String = apiVersion_example // kotlin.String | 
            //val xApiVersion : kotlin.String = xApiVersion_example // kotlin.String | 
            //val blogPostCategoryUpdateDto : BlogPostCategoryUpdateDto =  // BlogPostCategoryUpdateDto | 
            //val result : EmptyEnvelope = apiInstance.updateBlogPostCategoryAsync(blogPostCategoryId, tenantId, apiVersion, xApiVersion, blogPostCategoryUpdateDto)
            //result shouldBe ("TODO")
        }

    }
}
